### ISSUE TITLE
Crashed while exit limbo by dimdoors [DimensionalDoors]

### ISSUE THREAD

**Issue by leon7104** [zabi94/ExtraAlchemy#112]
---- Minecraft Crash Report ----
// You're mean.

Time: 13/7/2021 上午3:42
Description: Ticking entity

dev.onyxstudios.cca.internal.base.asm.StaticComponentLoadingException: Exception while registering static component factories for Extra Alchemy (extraalchemy)
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:157)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.init(StaticItemComponentPlugin.java:77)
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.getFactoryClass(StaticItemComponentPlugin.java:61)
	at dev.onyxstudios.cca.internal.item.CardinalItemInternals.createItemStackContainerFactory(CardinalItemInternals.java:45)
	at net.minecraft.class_1792.cardinal_createComponents(class_1792.java:1553)
	at net.minecraft.class_1799.getComponentContainer(class_1799.java:1793)
	at net.minecraft.class_2540.localvar$zge000$writeItemStackOptifine(class_2540.java:2082)
	at net.minecraft.class_2540.method_10793(class_2540.java)
	at org.dimdev.dimdoors.network.packet.s2c.PlayerInventorySlotUpdateS2CPacket.write(PlayerInventorySlotUpdateS2CPacket.java:40)
	at org.dimdev.dimdoors.network.ServerPacketHandler.sendPacket(ServerPacketHandler.java:64)
	at org.dimdev.dimdoors.network.ServerPacketHandler.sendPacket(ServerPacketHandler.java:73)
	at net.minecraft.class_3222.tryAddingFrayEnchantment(class_3222.java:1753)
	at net.minecraft.class_3222.handler$zze000$mobTickMixin(class_3222.java:1723)
	at net.minecraft.class_3222.method_5773(class_3222.java)
	at net.minecraft.class_3218.method_18762(class_3218.java:655)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:417)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:392)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:118)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'cardinal-components-item' provided by 'extraalchemy'
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:193)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:154)
	... 25 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: zabi.minecraft.extraalchemy.compat.CCACompatBridge
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	... 27 more
Caused by: java.lang.ClassNotFoundException: zabi.minecraft.extraalchemy.compat.CCACompatBridge
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dev.onyxstudios.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:157)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.init(StaticItemComponentPlugin.java:77)
	at dev.onyxstudios.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46)
	at dev.onyxstudios.cca.internal.item.StaticItemComponentPlugin.getFactoryClass(StaticItemComponentPlugin.java:61)
	at dev.onyxstudios.cca.internal.item.CardinalItemInternals.createItemStackContainerFactory(CardinalItemInternals.java:45)
	at net.minecraft.class_1792.cardinal_createComponents(class_1792.java:1553)
	at net.minecraft.class_1799.getComponentContainer(class_1799.java:1793)
	at net.minecraft.class_2540.localvar$zge000$writeItemStackOptifine(class_2540.java:2082)
	at net.minecraft.class_2540.method_10793(class_2540.java)
	at org.dimdev.dimdoors.network.packet.s2c.PlayerInventorySlotUpdateS2CPacket.write(PlayerInventorySlotUpdateS2CPacket.java:40)
	at org.dimdev.dimdoors.network.ServerPacketHandler.sendPacket(ServerPacketHandler.java:64)
	at org.dimdev.dimdoors.network.ServerPacketHandler.sendPacket(ServerPacketHandler.java:73)
	at net.minecraft.class_3222.tryAddingFrayEnchantment(class_3222.java:1753)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$znf000$fillPatchouliContext(class_128.java:1021)
	at net.minecraft.class_128.<init>(class_128.java:48)
	at net.minecraft.class_128.method_560(class_128.java:342)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:417)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:392)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:118)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 25
	Entity Name: Not_Existed
	Entity's Exact location: 11469.79, 69.00, 3744.28
	Entity's Block location: World: (11469,69,3744), Section: (at 13,5,0 in 716,4,234; chunk contains blocks 11456,0,3744 to 11471,255,3759), Region: (22,7; contains chunks 704,224 to 735,255, blocks 11264,0,3584 to 11775,255,4095)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Affected level --
Details:
	All players: 1 total; [class_3222['Not_Existed'/25, l='ServerLevel[新嘅世界]', x=11469.79, y=69.00, z=3744.28]]
	Chunk stats: 11228
	Level dimension: dimdoors:limbo
	Derived: true
	Level spawn location: World: (48,4,32), Section: (at 0,4,0 in 3,0,2; chunk contains blocks 48,0,32 to 63,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 98558 game time, 9033 day time
	Level name: 新嘅世界
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 730669944 bytes (696 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072.00
	Graphics card #0 deviceId: 0x1c02
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6663
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20158.00
	Virtual memory used (MB): 16281.39
	Swap memory total (MB): 3840.00
	Swap memory used (MB): 320.23
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 2.1.1+1.17.1
		appleskin: AppleSkin mc1.17-2.0.0
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterthirdperson: Better Third Person 1.5.0
		cardinal-components-base: Cardinal Components API (base) 3.0.0-nightly.1.17-pre2
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0-nightly.1.17-pre2
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0-nightly.1.17-pre2
		cardinal-components-item: Cardinal Components API (items) 3.0.0-nightly.1.17-pre2
		cardinal-components-level: Cardinal Components API (world saves) 3.0.0-nightly.1.17-pre2
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0-nightly.1.17-pre2
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0-nightly.1.17-pre2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_flowpowered_flow-math: flow-math 1.0.3
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		croptopia: Croptopia 1.5.0
		darkpaintings: Dark Paintings 3.0.6
		dimdoors: DimensionalDoors 4.0.0+beta.2-11.06.2021
		extraalchemy: Extra Alchemy 1.5.1
		fabric: Fabric API 0.36.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446313
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446313
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e13
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446313
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446313
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96913
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446313
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446313
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446313
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa13
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446313
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446313
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
		fabricloader: Fabric Loader 0.11.6
		fiber: fiber 0.23.0-2
		inventoryhud: Inventory HUD + 3.3.2
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.2+1.17.1
		libninepatch: LibNinePatch 1.1.0
		matrix: Matrix 1.0.0
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.2
		notenoughanimations: NotEnoughAnimations 1.3.0
		optifabric: OptiFabric 1.11.17
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		patchouli: Patchouli 1.17-54-FABRIC
		physicsmod: Physics Mod 1.0.0
		seedy-behavior: Seedy Behavior 1.0.1
		transliterationlib: TRansliterationLib 1.1.0
	Player Count: 1 / 8; [class_3222['Not_Existed'/25, l='ServerLevel[新嘅世界]', x=11469.79, y=69.00, z=3744.28]]
	Data Packs: vanilla (incompatible), Fabric Mods, dimdoors/classic, dimdoors/default
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	OptiFine Version: OptiFine_1.17.1_HD_U_G9_pre27
	OptiFine Build: 20210712-010127
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 466.63
	OpenGlRenderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17.1
	OptiFine jar version: OptiFine_1.17.1_HD_U_G9_pre27
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/leon0/AppData/Roaming/.minecraft/.optifine/OptiFine_1.17.1_HD_U_G9_pre27/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by leon7104** [comment]
thanks
