### ISSUE TITLE
[1.18.1] error when re-joining a server with the mod

### ISSUE THREAD

**Issue by Chuunkyz** [zabi94/ExtraAlchemy#130]
i'm using the mod is my modpack and there's currently a problem with servers, re-joining causes an error, the only way to fix is to restart the server
that's probably a conflict with bclib/betternether if i stick to the logs
of course, removing extra alchemy fixes the problem

[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] Received Hello from Client. (server=1.2.2, client=1.2.2)
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] Sending Hello to Client. (server=1.2.2)
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Listing Mod bclib v1.2.2 (size: 886.5 KiB, download=true)
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Listing Mod betternether v6.0.8 (size: 21.3 MiB, download=true)
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betternether.main
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betternether.generator
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betternether.blocks
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betternether.items
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betternether.mobs
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betternether.recipes
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_bclib.main
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_bclib.recipes
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betterend.entities
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betterend.blocks
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betterend.items
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betterend.biomes
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betterend.recipes
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Config bclib.CONFIG_betterend.enchantments
[29.01 19:49:51] [Server] [Server thread/INFO]: [bclib] 	- Offering Folder /bclib-sync (allowDelete=true)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: net/minecraft/class_310
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at zabi.minecraft.extraalchemy.items.PotionRingItem.method_7850(PotionRingItem.java:40)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1761.method_7738(class_1761.java:208)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder$1.method_7738(FabricItemGroupBuilder.java:129)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.packets.PolymerVanillaItemGroupEntry.of(PolymerVanillaItemGroupEntry.java:20)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.syncVanillaItemGroups(PolymerServerProtocol.java:283)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocolHandler.lambda$handleTooltipChange$0(PolymerServerProtocolHandler.java:74)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:151)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:125)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:110)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	... 19 more
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: net/minecraft/class_310
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at zabi.minecraft.extraalchemy.items.PotionRingItem.method_7850(PotionRingItem.java:40)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1761.method_7738(class_1761.java:208)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder$1.method_7738(FabricItemGroupBuilder.java:129)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.packets.PolymerVanillaItemGroupEntry.of(PolymerVanillaItemGroupEntry.java:20)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.syncVanillaItemGroups(PolymerServerProtocol.java:283)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.sendSyncPackets(PolymerServerProtocol.java:185)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocolHandler.lambda$handleSyncRequest$1(PolymerServerProtocolHandler.java:89)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:151)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:125)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:110)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
[29.01 19:49:51] [Server] [Server thread/INFO]: [STDERR]: 	... 20 more
[29.01 19:49:51] [Disconnect] ......... has disconnected, reasonDisconnected
[29.01 19:49:51] [Server] [Server thread/INFO]: ......... left the game

**Comment by zabi94** [comment]
Looks like a mod called polymer is calling a vanilla method wrongly. I'll try and see if I can solve this on my end.

Does uninstalling polymer fix the issue?

**Comment by Chuunkyz** [comment]
nvm, i found the issue, this was caused by bclib autosync

**Comment by eliskvitka** [comment]
> Looks like a mod called polymer is calling a vanilla method wrongly. I'll try and see if I can solve this on my end.
> 
> Does uninstalling polymer fix the issue?

I have similar error, but i don't have bclib or polymer installed. I think, this libs can be in some other mod jars
https://gist.github.com/braunly/15cc1a37a9e7ae5a033713c790b3d18a

UPD: i deleted mod with embedded Polymer library and error disappear
