### ISSUE TITLE
#Using potion bag in 1.12.2 Sponge server ticking players

### ISSUE THREAD

**Issue by LANCECHEN117** [zabi94/ExtraAlchemy#74]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(*)Bug

---

#### Version of the mod or build number:
>(*) extraalchemy-forge-1.12-build11-0.5.4

---

#### Are you a Single Player,  a Multiplayer Client (You are a player in a server) or Server Side?:
>(*)Multiplayer Client, sponge forge 2838-720

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(*) 1.12.2

---

#### Description (or what were you doing when it crashed):
>(*) Right using potion bag kick me out!!

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)  [minecraft/NetworkSystem]: Failed to handle packet for /106.59.245.15:56999
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$zik000$impl$onPlayerTick(NetHandlerPlayServer.java:2503) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.NullPointerException

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!) 

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!) 

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)Java8

---

#### Other information that you think might be useful:
>(-)

**Comment by zabi94** [comment]
I need a full log, not just the stack trace part, if that's possible. Fill the other fields where possible, this is not enough for me to fix things up.
Since the log is huge I'll ask you to use pastebin too, if possible, it will save me some time

**Comment by zabi94** [comment]
Also, please use pastebin

**Comment by zabi94** [comment]
I'll just assume this is not an issue of this mod
